# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-23 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='avatar',
            field=models.ImageField(blank=True, max_length=1000, upload_to='images/'),
        ),
    ]
