# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='phone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
